export const LOAD_CARS_SUCCESS = 'CARS_DATA/LOAD_SUCCESS';
export const LOAD_ALL_CARS_SUCCESS = 'CARS_DATA/ALL_LOAD_SUCCESS';
export const SHOW_CARS_LOADER = 'CARS_DATA/SHOW_LOADER';
export const HIDE_CARS_LOADER = 'CARS_DATA/HIDE_LOADER';
