export const LOAD_CATEGORY_SUCCESS = 'ENTITY_TYPES/LOAD_CATEGORY_SUCCESS';
export const SHOW_ENTITY_TYPES_LOADER = 'ENTITY_TYPES/SHOW_LOADER';
export const HIDE_ENTITY_TYPES_LOADER = 'ENTITY_TYPES/HIDE_LOADER';
